#!/bin/sh
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------
rm -rf [1-9]* 
rm -rf 0.*
rm -rf constant/polyMesh postProcessing processor*
rm -rf constant/extendedFeatureEdgeMesh
rm -rf constant/polyMesh
rm -rf log.*
rm -r pro*
rm -r lid.foam
rm -r cylinder.foam
rm -r poiseuille_2D.foam
rm -r logs
#------------------------------------------------------------------------------
